// 'use client'
import type { Metadata } from 'next'
import './globals.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { Box, Container } from '@mui/material';
import MiniDrawer from '@/components/sidebar/sidebar';
import { Roboto } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import theme from './theme/theme';

const roboto = Roboto({ subsets: ['latin'], weight: ["400", "500"] })

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>

        <Box sx={{ display: 'flex', marginTop: '100px' }} >
          <MiniDrawer />
          <Container fixed>
            <AppRouterCacheProvider>
              <ThemeProvider theme={theme}>{children}</ThemeProvider>;
            </AppRouterCacheProvider>
          </Container>
        </Box>

      </body>

    </html>
  )
}
